#!/bin/sh

echo "-----------------------"
echo "Beginning custom thing."
echo "Finished custom thing."
echo "-----------------------"
echo "${MY_ENV_VAR}"
echo "Adding this super important change from a forked version of the repo."
echo "trivial change... should run smoasdasdfasdfasdffkeasdfas on coasddfmmit"