#!/bin/sh

echo "-----------------------"
echo "Beginning custom thing."
echo "Finished custom thing."
echo "-----------------------"
echo "${MY_ENV_VAR}"
echo "Feature One Only"
echo "This is my new feature that conflicts with master."