#!/bin/sh

echo "-----------------------"
echo "Beginning custom thing."
echo "Finished custom thing."
echo "-----------------------"
echo "${MY_ENV_VAR}"
echo "Feature One Only"
echo "Master f1 conflict.. this feature was merged to master f1 from another member of the team."